# This is a basic workflow to help you get started with Actions

name: NASA HUD CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
    tags:
      - '*'
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  deploy-docker-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          BASE_PATH: './frontend'
        with:
          name: umgccaps/nasa.hud.client.dev
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          snapshot: true
          workdir: frontend

  deploy-docker-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          BASE_PATH: './backend'
        with:
          name: umgccaps/nasa.hud.server.dev
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          snapshot: true
          workdir: backend

  deploy-heroku-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_SERVER_DEV_NAME }}
        run: heroku container:login
      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
        working-directory: ./backend/
        run: heroku container:push web -a ${{ secrets.HEROKU_APP_SERVER_DEV_NAME }}
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
        working-directory: ./backend/
        run: heroku container:release web -a ${{ secrets.HEROKU_APP_SERVER_DEV_NAME }}

  deploy-heroku-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_CLIENT_DEV_NAME }}
        run: heroku container:login
      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
        working-directory: ./frontend/
        run: heroku container:push web -a ${{ secrets.HEROKU_APP_CLIENT_DEV_NAME }}
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
        working-directory: ./frontend/
        run: heroku container:release web -a ${{ secrets.HEROKU_APP_CLIENT_DEV_NAME }}
